import type { ReplayScenario } from "@/services/marketReplay/types"

export const mockReplayScenarios: ReplayScenario[] = [
  {
    id: "march-2024-ai-rotation",
    title: "Replay March 2024",
    dateRange: "01 Mar 2024 - 14 Mar 2024",
    durationDays: 14,
    thesis:
      "AI infrastructure narratives accelerate while liquidity rotates from speculative beta into infrastructure and productivity.",
    context:
      "The market is in a constructive regime with gradual volume expansion and improving news framing.",
    frames: [
      {
        day: 1,
        timestampLabel: "Day 1",
        narrativeLeader: "AI Infrastructure",
        narrativeStrength: 58,
        sentiment: 52,
        marketBreadth: 49,
        volumeTrend: "Neutral volume, early expansion phase",
        rotation: "Capital is still spread across memes, Layer 2, and AI",
        notableAssets: ["BTC", "ETH", "RNDR"],
      },
      {
        day: 3,
        timestampLabel: "Day 3",
        narrativeLeader: "AI Infrastructure",
        narrativeStrength: 66,
        sentiment: 57,
        marketBreadth: 54,
        volumeTrend: "Volume rises above the recent average",
        rotation: "Flow starts leaving memecoins for higher-beta AI names",
        notableAssets: ["RNDR", "TAO", "FET"],
      },
      {
        day: 5,
        timestampLabel: "Day 5",
        narrativeLeader: "AI Infrastructure",
        narrativeStrength: 73,
        sentiment: 61,
        marketBreadth: 59,
        volumeTrend: "Expansion confirms with clear follow-through",
        rotation: "Layer 2 cools while infrastructure takes leadership",
        notableAssets: ["TAO", "RNDR", "LINK"],
      },
      {
        day: 8,
        timestampLabel: "Day 8",
        narrativeLeader: "AI Infrastructure",
        narrativeStrength: 79,
        sentiment: 67,
        marketBreadth: 63,
        volumeTrend: "Volume stays strong, but becomes more selective",
        rotation: "Capital concentrates in narrative leaders",
        notableAssets: ["TAO", "FET", "LINK"],
      },
      {
        day: 11,
        timestampLabel: "Day 11",
        narrativeLeader: "AI Infrastructure",
        narrativeStrength: 83,
        sentiment: 71,
        marketBreadth: 60,
        volumeTrend: "Mild exhaustion signal in the long tail",
        rotation: "Internal rotation from high beta into higher-quality names",
        notableAssets: ["TAO", "LINK", "ETH"],
      },
      {
        day: 14,
        timestampLabel: "Day 14",
        narrativeLeader: "AI Infrastructure",
        narrativeStrength: 76,
        sentiment: 64,
        marketBreadth: 56,
        volumeTrend: "Volume cools after the peak",
        rotation: "The market takes partial profits and consolidates gains",
        notableAssets: ["ETH", "LINK", "BTC"],
      },
    ],
    events: [
      {
        id: "ev-1",
        day: 1,
        timestampLabel: "Day 1",
        title: "AI starts dominating headlines",
        description: "A framing shift across news and social channels prioritizes infrastructure and productivity.",
        impact: "medium",
        category: "narrative",
      },
      {
        id: "ev-2",
        day: 4,
        timestampLabel: "Day 4",
        title: "Memecoins rotate into AI",
        description: "Speculative flow reduces meme exposure and increases narrative beta in AI.",
        impact: "high",
        category: "rotation",
      },
      {
        id: "ev-3",
        day: 7,
        timestampLabel: "Day 7",
        title: "Sentiment improves with volume",
        description: "Market participation broadens and headlines reinforce thematic continuity.",
        impact: "medium",
        category: "sentiment",
      },
      {
        id: "ev-4",
        day: 10,
        timestampLabel: "Day 10",
        title: "Quality starts to lead",
        description: "The market reduces risk in fragile names and concentrates liquidity in leaders.",
        impact: "medium",
        category: "volume",
      },
      {
        id: "ev-5",
        day: 13,
        timestampLabel: "Day 13",
        title: "Breadth starts to slow",
        description: "Lower positive dispersion suggests a need for partial profit-taking.",
        impact: "low",
        category: "macro",
      },
    ],
    outcomes: [
      { label: "Narrative Peak", value: "83", tone: "positive" },
      { label: "Best Rotation", value: "Memes -> AI Infra", tone: "positive" },
      { label: "Risk State", value: "Concentration Rising", tone: "neutral" },
      { label: "Close", value: "Trend intact, breadth softer", tone: "neutral" },
    ],
    followThrough: [
      {
        horizon: "30d",
        whatHappenedNext:
          "AI infrastructure remained the winning narrative while quality outperformed higher-beta tails.",
        marketEvolution:
          "Leadership stayed concentrated, returns persisted, and market breadth softened moderately.",
        winningNarratives: ["AI Infrastructure", "Quality", "Productivity"],
        losingNarratives: ["Memecoins", "High-beta tails"],
      },
      {
        horizon: "60d",
        whatHappenedNext:
          "Leadership broadened into selected majors, but narrative intensity normalized from peak levels.",
        marketEvolution:
          "Rotation matured from discovery into selective follow-through with lower asymmetry.",
        winningNarratives: ["Infrastructure", "Majors with utility"],
        losingNarratives: ["Late beta chasers", "Thin-liquidity names"],
      },
      {
        horizon: "90d",
        whatHappenedNext:
          "The original thesis remained directionally correct, but fresh alpha shifted from narrative acceleration to execution quality.",
        marketEvolution:
          "Market regime stayed constructive, yet concentration risk required more disciplined position sizing.",
        winningNarratives: ["Execution quality", "Institutional liquidity"],
        losingNarratives: ["Narrative-only momentum"],
      },
    ],
    lessons: [
      "A strong narrative with only moderate breadth can still continue if leadership keeps the volume.",
      "Internal rotation from beta into quality usually precedes a slowdown, not an immediate reversal.",
      "Partial profit-taking near the narrative-strength peak improves re-entry asymmetry.",
    ],
  },
]

